import opengl_gl_libs = opengl-meta%lib{opengl-gl}
import opengl_glu_libs = opengl-meta%lib{opengl-glu}
import opengl_glut_libs = opengl-meta%lib{opengl-glut}
import opengl_egl_libs = opengl-meta%lib{opengl-egl}
import opengl_gles_libs = opengl-meta%lib{opengl-gles}

c.libs = -lm

./: exe{driver_glut} exe{driver_gles}

exe{driver_glut}: c{driver_glut} $opengl_gl_libs $opengl_glu_libs $opengl_glut_libs

exe{driver_gles}: c{driver_gles} $opengl_gl_libs $opengl_egl_libs $opengl_gles_libs